# Generated by Django 4.0.4 on 2022-05-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drivetest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uploadedFile', models.FileField(upload_to='Files/')),
                ('date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('extra', models.FileField(upload_to='Extra/')),
            ],
        ),
    ]
