# Generated by Django 4.0.4 on 2022-05-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivetest',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
