# Generated by Django 4.0.4 on 2022-05-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_alter_drivetest_date_alter_drivetest_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivetest',
            name='date',
        ),
    ]
