# Generated by Django 4.0.4 on 2022-05-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_remove_drivetest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivetest',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='drivetest',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='drivetest',
            name='uploadedFile',
        ),
    ]
