# Generated by Django 4.0.4 on 2022-05-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_remove_drivetest_date_created_remove_drivetest_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivetest',
            name='uploadedFile',
            field=models.FileField(default=None, upload_to='Files/'),
        ),
    ]
