# Generated by Django 4.0.4 on 2022-05-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_drivetest_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivetest',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='drivetest',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='drivetest',
            name='extra',
            field=models.FileField(default=None, upload_to='Extra/'),
        ),
    ]
