# Generated by Django 4.0.4 on 2022-06-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0007_drivetest_date_drivetest_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivetest',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='drivetest',
            name='uploadedFile',
        ),
        migrations.AddField(
            model_name='drivetest',
            name='bill',
            field=models.FileField(default=None, upload_to='bill/'),
        ),
        migrations.AddField(
            model_name='drivetest',
            name='csv',
            field=models.FileField(default=None, upload_to='csv/'),
        ),
        migrations.AddField(
            model_name='drivetest',
            name='kml',
            field=models.FileField(default=None, upload_to='kml/'),
        ),
    ]
