# Generated by Django 4.0.4 on 2022-06-15 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0008_remove_drivetest_extra_remove_drivetest_uploadedfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivetest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drivetest',
            name='bill',
            field=models.FileField(blank=True, default=None, upload_to='bill/'),
        ),
    ]
