# Generated by Django 4.0.4 on 2022-06-15 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0009_drivetest_user_alter_drivetest_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivetest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
